# Spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1384g0a656991q8do.mysql.rds.aliyuncs.com:3306/alt?createDatabaseIfNotExist=true
    username: root
    password: Wetech1234
    # data:
    #   - classpath:initialdata/user.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false

# Server
server:
  port: 443
  ssl:
    key-store: classpath:newpictown.jks
    key-password: 214040872140141
    key-store-type: JKS